# SPDX-License-Identifier: GPL-2.0

load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//build/bazel_common_rules/dist:dist.bzl", "copy_to_dist_dir")
load("//build/bazel_common_rules/exec:exec.bzl", "exec")
load("//build/kernel/kleaf:hermetic_tools.bzl", "hermetic_genrule")
load(
    "//build/kernel/kleaf:kernel.bzl",
    "kernel_abi",
    "kernel_build",
    "kernel_build_config",
    "kernel_images",
    "kernel_module",
    "kernel_module_group",
    "kernel_modules_install",
    "kernel_unstripped_modules_archive",
    "merged_kernel_uapi_headers",
)
load("//common:modules.bzl", "get_gki_modules_list")

_SOC_REVS = [
    "a0",
    "b0",
]

_FELIX_DTBOS = [
    # Sync with build.config.felix
    "gs201-felix-dev1_0.dtbo",
    "gs201-felix-proto1_0.dtbo",
    "gs201-felix-proto1_0_testDDR.dtbo",
    "gs201-felix-proto1_1.dtbo",
    "gs201-felix-proto1_1_testDDR.dtbo",
    "gs201-felix-evt1_0.dtbo",
    "gs201-felix-evt1_0-wingboard.dtbo",
    "gs201-felix-evt1_0-doe.dtbo",
    "gs201-felix-dvt1_0.dtbo",
    "gs201-felix-pvt1_0.dtbo",
    "gs201-felix-mp.dtbo",
]

kernel_module_group(
    name = "felix_ext_modules",
    srcs = [
        # do not sort
        "//private/devices/google/felix:gs201_soc.felix",
        "//private/devices/google/felix/display:drm_panel.google",
        "//private/google-modules/display/common/gs_drm",
        "//private/google-modules/display/common/gs_panel",
        "//private/google-modules/display/samsung:display.samsung",
        "//private/google-modules/gpu/mali_kbase",
        "//private/google-modules/gpu/mali_pixel",
        "//private/google-modules/edgetpu/janeiro/drivers/edgetpu:edgetpu.janeiro",
        "//private/google-modules/fingerprint/fpc",
        "//private/google-modules/gps/broadcom/bcm47765",
        "//private/google-modules/gxp/gs201:gxp",
        "//private/google-modules/bms",
        "//private/google-modules/bms/misc:bms-misc",
        "//private/google-modules/power/mitigation:bcl",
        "//private/google-modules/power/reset",
        "//private/google-modules/radio/samsung/s5300:cpif",
        "//private/google-modules/lwis",
        "//private/google-modules/misc/sscoredump",
        "//private/google-modules/amplifiers/audiometrics",
        "//private/google-modules/amplifiers/snd_soc_wm_adsp:snd-soc-wm-adsp",
        "//private/google-modules/amplifiers/cs35l41",
        "//private/google-modules/amplifiers/cs35l45",
        "//private/google-modules/amplifiers/cs40l26",
        "//private/google-modules/amplifiers/drv2624",
        "//private/google-modules/aoc",
        "//private/google-modules/aoc/alsa",
        "//private/google-modules/aoc/usb:aoc.usb",
        "//private/devices/google/felix/touch/fst2",
        "//private/devices/google/felix/touch/ftm5",
        "//private/google-modules/nfc",
        "//private/google-modules/touch/common:touch.common",
        "//private/google-modules/trusty",
        "//private/google-modules/uwb/qorvo/dw3000/kernel:uwb.dw3000",
        "//private/google-modules/video/gchips:video.gchips",
        "//private/google-modules/bluetooth/broadcom:bluetooth.broadcom",
        "//private/google-modules/wlan/bcm4389:bcmdhd4389",
    ],
)

kernel_build(
    name = "gs201_felix",
    srcs = glob([
        "build.config.*",
        "dts/**",
        "felix*.fragment",
    ]) + [
        # keep sorted
        "//common:kernel_aarch64_sources",
        "//private/devices/google/felix/touch/fst2:fst2.kconfig",
        "//private/devices/google/felix/touch/ftm5:ftm5.kconfig",
        "//private/devices/google/gs201:build.config.gs201",
        "//private/google-modules/bms/misc:bms-misc.kconfig",
        "//private/google-modules/display/common:common.kconfig",
        "//private/google-modules/display/samsung:display.samsung.kconfig",
        "//private/google-modules/fingerprint/qcom/qfs4008:qbt_handler.kconfig",
        "//private/google-modules/power/mitigation:bcl.kconfig",
        "//private/google-modules/power/reset:reset.kconfig",
        "//private/google-modules/radio/samsung/s5300:cpif.kconfig",
        "//private/google-modules/radio/samsung/s5400:cpif.kconfig",
        "//private/google-modules/soc/gs:gs_soc.kconfig",
        "//private/google-modules/touch/common:touch.common.kconfig",
        "//private/google-modules/touch/fts/ftm5:ftm5.kconfig",
        "//private/google-modules/touch/sec:sec.kconfig",
        "//private/google-modules/trusty:trusty.kconfig",
        "//private/google-modules/wlan/wlan_ptracker:wlan_ptracker.kconfig",
    ],
    outs = [
        "google-base/gs201-{}.dtb".format(soc_rev)
        for soc_rev in _SOC_REVS
    ] + _FELIX_DTBOS,
    base_kernel = "//common:kernel_aarch64_download_or_build",
    build_config = ":felix_build_config",
    collect_unstripped_modules = True,
    dtstree = "//private/devices/google/felix/dts:felix.dt",
    kconfig_ext = "//private/google-modules/soc/gs:Kconfig.ext",
    kmi_symbol_list = "//common:android/abi_gki_aarch64_pixel",
    make_goals = [
        "modules",
        "dtbs",
    ],
    module_outs = [
        # keep sorted
        "crypto/crct10dif_common.ko",
        "crypto/crct10dif_generic.ko",
        "drivers/block/null_blk/null_blk.ko",
        "drivers/gpu/drm/display/drm_display_helper.ko",
        "drivers/hwtracing/coresight/coresight.ko",
        "drivers/hwtracing/coresight/coresight-etm4x.ko",
        "drivers/hwtracing/coresight/coresight-funnel.ko",
        "drivers/hwtracing/coresight/coresight-replicator.ko",
        "drivers/hwtracing/coresight/coresight-tmc.ko",
        "drivers/i2c/i2c-dev.ko",
        "drivers/misc/eeprom/at24.ko",
        "drivers/perf/arm_dsu_pmu.ko",
        "drivers/scsi/scsi_debug.ko",
        "drivers/scsi/sg.ko",
        "drivers/spi/spidev.ko",
        "drivers/watchdog/softdog.ko",
        "lib/crc-t10dif.ko",
        "net/mac80211/mac80211.ko",
        "net/wireless/cfg80211.ko",
    ],
    strip_modules = True,
    visibility = [
        # keep sorted
        "//private/google-modules:__subpackages__",
    ],
)

kernel_abi(
    name = "gs201_felix_abi",
    kernel_build = ":gs201_felix",
    kernel_modules = [":felix_ext_modules"],
    kmi_symbol_list_add_only = True,
    module_grouping = False,
)

kernel_module(
    name = "gs201_soc.felix",
    srcs = [
        "//private/google-modules/soc/gs:gs_soc_sources",
        "//private/google-modules/trusty:headers",
    ],
    outs = [
        # keep sorted
        "drivers/block/zram/zcomp_cpu.ko",
        "drivers/block/zram/zcomp_eh.ko",
        "drivers/block/zram/zram_gs.ko",
        "drivers/bts/bts.ko",
        "drivers/clk/gs/clk_exynos_gs.ko",
        "drivers/clocksource/exynos_mct.ko",
        "drivers/cpufreq/exynos-acme.ko",
        "drivers/devfreq-whi/google/arm-memlat-mon.ko",
        "drivers/devfreq-whi/google/exynos_devfreq.ko",
        "drivers/devfreq-whi/google/governor_memlat.ko",
        "drivers/devfreq-whi/google/memlat-devfreq.ko",
        "drivers/dma-buf/heaps/samsung/samsung_dma_heap.ko",
        "drivers/dma/pl330.ko",
        "drivers/dma/samsung-dma.ko",
        "drivers/gpu/exynos/g2d/g2d.ko",
        "drivers/i2c/busses/i2c-acpm.ko",
        "drivers/i2c/busses/i2c-exynos5.ko",
        "drivers/iio/power/odpm-whi.ko",
        "drivers/input/fingerprint/goodixfp.ko",
        "drivers/input/keyboard/s2mpg12-key.ko",
        "drivers/input/keycombo.ko",
        "drivers/input/keydebug.ko",
        "drivers/input/misc/vl53l1/stmvl53l1.ko",
        "drivers/iommu/exynos-pcie-iommu.ko",
        "drivers/iommu/samsung-iommu-group.ko",
        "drivers/iommu/samsung-secure-iova.ko",
        "drivers/iommu/samsung_iommu.ko",
        "drivers/media/platform/exynos/mfc/exynos_mfc.ko",
        "drivers/media/platform/exynos/smfc/smfc.ko",
        "drivers/mfd/s2mpg12-mfd.ko",
        "drivers/mfd/s2mpg13-mfd.ko",
        "drivers/mfd/s2mpg1x-gpio.ko",
        "drivers/mfd/slg51000-core.ko",
        "drivers/mfd/slg51002-core.ko",
        "drivers/misc/sbb-mux/sbb-mux.ko",
        "drivers/misc/sscoredump/sscoredump.ko",
        "drivers/pci/controller/dwc-whi/pcie-exynos-gs.ko",
        "drivers/pci/controller/dwc-whi/pcie-exynos-gs201-rc-cal.ko",
        "drivers/phy/samsung/phy-exynos-mipi.ko",
        "drivers/phy/samsung/phy-exynos-mipi-dsim.ko",
        "drivers/phy/samsung/phy-exynos-usbdrd-super.ko",
        "drivers/pinctrl/gs/pinctrl-exynos-gs.ko",
        "drivers/pinctrl/pinctrl-slg51000.ko",
        "drivers/pinctrl/pinctrl-slg51002.ko",
        "drivers/power/reset/debug-reboot.ko",
        "drivers/regulator/pmic_class.ko",
        "drivers/regulator/s2mpg12-powermeter.ko",
        "drivers/regulator/s2mpg12-regulator.ko",
        "drivers/regulator/s2mpg13-powermeter.ko",
        "drivers/regulator/s2mpg13-regulator.ko",
        "drivers/regulator/slg51000-regulator.ko",
        "drivers/regulator/slg51002-regulator.ko",
        "drivers/rtc/rtc-s2mpg12.ko",
        "drivers/scsi/ufs/ufs-exynos-gs.ko",
        "drivers/soc/google/acpm/acpm_flexpmu_dbg.ko",
        "drivers/soc/google/acpm/acpm_mbox_test.ko",
        "drivers/soc/google/acpm/gs_acpm.ko",
        "drivers/soc/google/acpm/power_stats.ko",
        "drivers/soc/google/bcm_dbg.ko",
        "drivers/soc/google/cal-if/cmupmucal.ko",
        "drivers/soc/google/dbgcore-dump.ko",
        "drivers/soc/google/debug/debug-snapshot-debug-kinfo.ko",
        "drivers/soc/google/debug/dss.ko",
        "drivers/soc/google/debug/ehld.ko",
        "drivers/soc/google/debug/etm2dram.ko",
        "drivers/soc/google/debug/exynos-adv-tracer.ko",
        "drivers/soc/google/debug/exynos-adv-tracer-s2d.ko",
        "drivers/soc/google/debug/exynos-coresight.ko",
        "drivers/soc/google/debug/exynos-coresight-etm.ko",
        "drivers/soc/google/debug/exynos-debug-test.ko",
        "drivers/soc/google/debug/exynos-ecc-handler.ko",
        "drivers/soc/google/debug/itmon.ko",
        "drivers/soc/google/debug/pixel-boot-metrics.ko",
        "drivers/soc/google/debug/pixel-debug-test.ko",
        "drivers/soc/google/debug/pixel-suspend-diag.ko",
        "drivers/soc/google/debug/sjtag-driver.ko",
        "drivers/soc/google/ect_parser.ko",
        "drivers/soc/google/eh/eh.ko",
        "drivers/soc/google/exynos-bcm_dbg-dump.ko",
        "drivers/soc/google/exynos-cpuhp.ko",
        "drivers/soc/google/exynos-cpupm.ko",
        "drivers/soc/google/exynos-dm.ko",
        "drivers/soc/google/exynos-pd.ko",
        "drivers/soc/google/exynos-pd-dbg.ko",
        "drivers/soc/google/exynos-pd_el3.ko",
        "drivers/soc/google/exynos-pd_hsi0.ko",
        "drivers/soc/google/exynos-pm.ko",
        "drivers/soc/google/exynos-pmu-if.ko",
        "drivers/soc/google/exynos-seclog.ko",
        "drivers/soc/google/exynos_pm_qos.ko",
        "drivers/soc/google/gs-chipid.ko",
        "drivers/soc/google/gsa/gsa.ko",
        "drivers/soc/google/gsa/gsa_gsc.ko",
        "drivers/soc/google/hardlockup-debug.ko",
        "drivers/soc/google/hardlockup-watchdog.ko",
        "drivers/soc/google/kernel-top.ko",
        "drivers/soc/google/pixel_stat/mm/pixel_stat_mm.ko",
        "drivers/soc/google/pixel_stat/pixel_stat_sysfs.ko",
        "drivers/soc/google/pkvm-s2mpu/pkvm-s2mpu/pkvm-s2mpu.ko",
        "drivers/soc/google/pt/slc_acpm.ko",
        "drivers/soc/google/pt/slc_dummy.ko",
        "drivers/soc/google/pt/slc_pmon.ko",
        "drivers/soc/google/pt/slc_pt.ko",
        "drivers/soc/google/sysrq-hook.ko",
        "drivers/soc/google/vh/kernel/cgroup/vh_cgroup.ko",
        "drivers/soc/google/vh/kernel/fs/vh_fs.ko",
        "drivers/soc/google/vh/kernel/metrics/pixel_metrics.ko",
        "drivers/soc/google/vh/kernel/mm/vh_mm.ko",
        "drivers/soc/google/vh/kernel/pixel_em/pixel_em.ko",
        "drivers/soc/google/vh/kernel/sched/sched_tp.ko",
        "drivers/soc/google/vh/kernel/sched/vh_preemptirq_long.ko",
        "drivers/soc/google/vh/kernel/sched/vh_sched.ko",
        "drivers/soc/google/vh/kernel/systrace.ko",
        "drivers/soc/google/vh/kernel/thermal/vh_thermal.ko",
        "drivers/spi/spi-s3c64xx.ko",
        "drivers/thermal/google/s2mpg13_spmic_thermal.ko",
        "drivers/thermal/samsung/gpu_cooling.ko",
        "drivers/thermal/samsung/gs_thermal.ko",
        "drivers/tty/serial/exynos_tty.ko",
        "drivers/ufs/ufs-exynos-gs.ko",
        "drivers/usb/dwc3/dwc3-exynos-usb.ko",
        "drivers/usb/gadget/function/usb_f_dm.ko",
        "drivers/usb/gadget/function/usb_f_dm1.ko",
        "drivers/usb/gadget/function/usb_f_etr_miu.ko",
        "drivers/usb/host/xhci-exynos.ko",
        "drivers/usb/typec/tcpm/google/bc_max77759.ko",
        "drivers/usb/typec/tcpm/google/google_tcpci_shim.ko",
        "drivers/usb/typec/tcpm/google/max77759_contaminant.ko",
        "drivers/usb/typec/tcpm/google/max77759_helper.ko",
        "drivers/usb/typec/tcpm/google/max77779_contaminant.ko",
        "drivers/usb/typec/tcpm/google/max777x9_contaminant.ko",
        "drivers/usb/typec/tcpm/google/tcpci_max77759.ko",
        "drivers/usb/typec/tcpm/google/usb_psy.ko",
        "drivers/usb/typec/tcpm/google/usbc_cooling_dev.ko",
        "drivers/watchdog/s3c2410_wdt.ko",
    ],
    kernel_build = "//private/google-modules/soc/gs:gs_kernel_build",
    makefile = ["//private/google-modules/soc/gs:Makefile"],
    visibility = [
        # keep sorted
        "//private/devices/google:__subpackages__",
        "//private/google-modules:__subpackages__",
    ],
    deps = [
        "//private/google-modules/bms/misc:bms-misc",
        "//private/google-modules/trusty",
    ],
)

kernel_modules_install(
    name = "gs201_felix_modules_install",
    kernel_build = ":gs201_felix",
    kernel_modules = [":felix_ext_modules"],
)

merged_kernel_uapi_headers(
    name = "gs201_felix_merged_uapi_headers",
    kernel_build = ":gs201_felix",
    kernel_modules = [":felix_ext_modules"],
)

kernel_unstripped_modules_archive(
    name = "gs201_felix_unstripped_modules_archive",
    kernel_build = ":gs201_felix",
    kernel_modules = [":felix_ext_modules"],
)

hermetic_genrule(
    name = "vendor_kernel_boot_modules.felix-cat",
    srcs = [
        "vendor_kernel_boot_modules.felix",
        "//private/devices/google/gs201:vendor_kernel_boot_modules.gs201",
    ],
    outs = [
        "vendor_kernel_boot_modules.concat",
    ],
    cmd = """
        cat $(location vendor_kernel_boot_modules.felix) \\
            $(location //private/devices/google/gs201:vendor_kernel_boot_modules.gs201) \\
            > $@
    """,
)

# Don't load the zram GKI module
_GKI_MODULES_LIST = [m for m in get_gki_modules_list("arm64") if not m.endswith("zram.ko")]

write_file(
    name = "system_dlkm_modules_list",
    out = "system_dlkm_modules_list.felix",
    content = _GKI_MODULES_LIST,
)

kernel_images(
    name = "gs201_felix_images",
    base_kernel_images = "//common:kernel_aarch64_images_download_or_build",
    boot_image_outs = ["dtb.img"],
    build_boot = False,
    build_dtbo = True,
    build_initramfs = True,
    build_system_dlkm = True,
    build_vendor_dlkm = True,
    build_vendor_kernel_boot = True,
    dedup_dlkm_modules = True,
    dtbo_srcs = [":gs201_felix/" + file for file in _FELIX_DTBOS],
    kernel_build = ":gs201_felix",
    kernel_modules_install = ":gs201_felix_modules_install",
    # Keep the following in sync with build.config.felix:
    modules_list = ":vendor_kernel_boot_modules.felix-cat",
    system_dlkm_modules_list = ":system_dlkm_modules_list",
    system_dlkm_props = "//private/devices/google/gs201:system_dlkm.props.gs201",
    #vendor_dlkm_etc_files = ["//private/devices/google/felix:insmod_cfgs"],
    vendor_dlkm_modules_blocklist = "//private/devices/google/gs201:vendor_dlkm.blocklist.gs201",
    # No MODULES_BLOCKLIST
    vendor_dlkm_modules_list = "//private/devices/google/gs201:vendor_dlkm_modules.gs201",
    vendor_dlkm_props = "//private/devices/google/gs201:vendor_dlkm.props.gs201",
    deps = [
        # Keep the following in sync with vendor_dlkm.props:
        # selinux_fc
        "//private/devices/google/common:sepolicy",
    ],
)

#filegroup(
#    name = "insmod_cfgs",
#    srcs = glob([
#        "insmod_cfg/*.cfg",
#    ]),
#)

_gs201_felix_dist_targets = [
    ":gs201_felix",
    ":gs201_felix_images",
    # At the time of writing (2022-02-04), this intentionally diverges from
    # the behavior of build.sh-style mixed builds by also incorporating
    # UAPI headers of external modules, while build.sh-style mixed builds
    # always uses kernel-uapi-headers.tar.gz from GKI_DIST_DIR.
    # To use GKI's kernel-uapi-headers.tar.gz in DIST_DIR, use
    #     //common:kernel_aarch64_uapi_headers
    # instead.
    ":gs201_felix_merged_uapi_headers",
    ":gs201_felix_modules_install",
    ":gs201_felix_unstripped_modules_archive",
    #":insmod_cfgs",
    "//common:android/abi_gki_aarch64_pixel",
    "//common:kernel_aarch64_download_or_build",
    "//common:kernel_aarch64_headers_download_or_build",
    "//private/devices/google/pantah:gki_aarch64_boot",
    "//private/devices/google/pantah:gs201_pantah_extracted_system_dlkm",
] + select({
    "//private/devices/google/common:enable_download_fips140": ["@gki_prebuilt_fips140//fips140.ko"],
    "//private/devices/google/common:disable_download_fips140": [],
})

copy_to_dist_dir(
    name = "gs201_felix_dist_copy_to_dist_dir",
    data = _gs201_felix_dist_targets,
    dist_dir = "out/felix/dist",
    flat = True,
    log = "info",
)

exec(
    name = "gs201_felix_dist",
    data = [":gs201_felix_dist_copy_to_dist_dir"],
    script = """
        echo {gki_kernel_dir}: $(git -C $BUILD_WORKSPACE_DIRECTORY/{gki_kernel_dir} rev-parse HEAD)
        $(rootpath :gs201_felix_dist_copy_to_dist_dir) $@
    """.format(gki_kernel_dir = "//aosp"),
)

kernel_build_config(
    name = "felix_build_config",
    srcs = [
        # do not sort
        "//common:set_kernel_dir_build_config",
        "build.config.felix",
    ],
)
