# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "kernel_dtstree")

kernel_dtstree(
    name = "tangorpro.dt",
    srcs = glob([
        "Makefile",
        "google/Makefile",
        "google/*.dtsi",
        "google/*.dts",
        "google/google-dts-base",
        "google/google-dts-base/Makefile",
        "google/google-dts-base/*.dts",
        "google/google-dts-base/*.dtsi",
    ]) + [
        "//private/google-modules/whi-staging/soc/gs:gs.dt-bindings",
    ],
    visibility = [
        "//private/devices/google/tangorpro:__pkg__",
        "//private/google-modules/whi-staging/soc/gs:__pkg__",
    ],
)
