# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DRM_PANEL_GOOGLE_BIGSURF)		+= panel-google-bigsurf.o
obj-$(CONFIG_DRM_PANEL_GOOGLE_SHORELINE)	+= panel-google-shoreline.o
obj-$(CONFIG_DRM_PANEL_GOOGLE_TG4A)		+= panel-google-tg4a.o
obj-$(CONFIG_DRM_PANEL_GOOGLE_TG4B)		+= panel-google-tg4b.o
