# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

filegroup(
    name = "fst2.kconfig",
    srcs = glob([
        "Kconfig",
    ]),
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/whi-staging/soc/gs:__pkg__",
    ],
)

kernel_module(
    name = "fst2",
    srcs = glob([
        "**/*.c",
        "**/*.h",
        "Kbuild",
    ]) + [
        "//private/google-modules/whi-staging/display:headers",
        "//private/google-modules/whi-staging/display/include:headers",
        "//private/google-modules/whi-staging/soc/gs:gs_soc_headers",
        "//private/google-modules/whi-staging/touch/common:headers",
    ],
    outs = [
        "fst2.ko",
    ],
    kernel_build = "//private/google-modules/whi-staging/soc/gs:gs_kernel_build",
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/whi-staging/soc/gs:__pkg__",
    ],
    deps = [
        "//private/google-modules/whi-staging/soc/gs:gs_soc_module",
        "//private/google-modules/whi-staging/touch/common:touch.common",
    ],
)
