# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/../private/google-modules/whi-staging/display
ccflags-y += -I$(srctree)/../private/google-modules/whi-staging/display/include/uapi
ccflags-y += -I$(srctree)/../private/google-modules/whi-staging/touch/common
ccflags-y += -I$(srctree)/../private/google-modules/whi-staging/touch/common/include

# FTM5 support
obj-$(CONFIG_TOUCHSCREEN_FST2)	+= fst2.o
fst2-objs = fts.o fts_proc.o
fst2-objs += \
	fts_lib/fts_flash.o fts_lib/fts_io.o fts_lib/fts_test.o

